### ISSUE TITLE
meter-reader crashes randomly multiple times per week

### ISSUE THREAD

**Issue by stefbontinckx** [jhhbe/hassio-addons#4]
Hi, 

Thank you for creating this add-on, it's amazing for my analogue meter and AWS provides the best image recognition it seems compared to other add-ons I have tried. 

The add-on crashes randomly at some times, and does not restart automatically. 

It appears it's the "Max retries exceeded with url: /local/tmp/meter.jpg" which points to a snapshot of my camera feed. 

How can I resolve this? 
Would it be possible to enter an interal path in the 'url' field? Or does it need to be the external path with authentication?

Thanks! 

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Meter reader
 Put a webcam in front of your utility meter and let AWS push the reading over mqtt
-----------------------------------------------------------
 Add-on version: 0.1.5
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[23:26:24] ERROR: Unknown HTTP error occured
 System:   (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2023.1.1
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Successfully created the directory /root/.aws 
Start
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa3045a90>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxx.duckdns.org', port=8123): Max retries exceeded with url: /local/tmp/meter.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa3045a90>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "ocr_aws.py", line 107, in <module>
    takereading()
  File "ocr_aws.py", line 80, in takereading
    r = requests.get(config_json["url"], auth=(config_json["user"], config_json["password"]))
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='xxx.duckdns.org', port=8123): Max retries exceeded with url: /local/tmp/meter.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa3045a90>: Failed to establish a new connection: [Errno -3] Try again'))
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by stefbontinckx** [comment]
This was caused by using the external url via duckdns, when duckdns was down the add-on crashes because the image could not be fetched. I switched to the local URL after setting up NGINX.
